### ISSUE TITLE
'python setup.py develop' returns error on CMakeLists.txt

### ISSUE THREAD

**Issue by qzhang234** [pyxpcs/pyxpcs#3]
I'm trying to run `python setup.py develop` and I get the following error:

<details>
<summary> Error from terminal </summary>

```

(VirEnv) sodalite:pyxpcs-master qzhang234$ 
(VirEnv) sodalite:pyxpcs-master qzhang234$ 
(VirEnv) sodalite:pyxpcs-master qzhang234$ python setup.py develop
running develop
running egg_info
writing src/pyxpcs.egg-info/PKG-INFO
writing dependency_links to src/pyxpcs.egg-info/dependency_links.txt
writing top-level names to src/pyxpcs.egg-info/top_level.txt
reading manifest file 'src/pyxpcs.egg-info/SOURCES.txt'
writing manifest file 'src/pyxpcs.egg-info/SOURCES.txt'
running build_ext
-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
CMake Error at CMakeLists.txt:12 (add_subdirectory):
  The source directory

    /Users/qzhang234/Work/Code_Projects/pyxpcs-master/lib/pybind11

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:13 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".


-- Configuring incomplete, errors occurred!
See also "/Users/qzhang234/Work/Code_Projects/pyxpcs-master/build/temp.macosx-10.7-x86_64-3.7/CMakeFiles/CMakeOutput.log".
See also "/Users/qzhang234/Work/Code_Projects/pyxpcs-master/build/temp.macosx-10.7-x86_64-3.7/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 75, in <module>
    zip_safe=False,
  File "/opt/anaconda3/envs/VirEnv/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/opt/anaconda3/envs/VirEnv/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/anaconda3/envs/VirEnv/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/anaconda3/envs/VirEnv/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/anaconda3/envs/VirEnv/lib/python3.7/site-packages/setuptools/command/develop.py", line 38, in run
    self.install_for_development()
  File "/opt/anaconda3/envs/VirEnv/lib/python3.7/site-packages/setuptools/command/develop.py", line 140, in install_for_development
    self.run_command('build_ext')
  File "/opt/anaconda3/envs/VirEnv/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/anaconda3/envs/VirEnv/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 32, in run
    self.build_extension(ext)
  File "setup.py", line 60, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/opt/anaconda3/envs/VirEnv/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/Users/qzhang234/Work/Code_Projects/pyxpcs-master', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/qzhang234/Work/Code_Projects/pyxpcs-master/src/', '-DPYTHON_EXECUTABLE=/opt/anaconda3/envs/VirEnv/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
(VirEnv) sodalite:pyxpcs-master qzhang234$ 
(VirEnv) sodalite:pyxpcs-master qzhang234$ 

```

</details>

Any suggestions?

**Comment by qzhang234** [comment]
Meeting on 05/28: New local library created and synced with current GitHub repo.

New error message occurred. Faisal commented that the code is not designed to run with MacOS so some tweaking is required.

<details>
<summary> Error from terminal </summary>

```

(VirEnv) sodalite:pyxpcs qzhang234$ python setup.py develop
running develop
running egg_info
creating src/pyxpcs.egg-info
writing src/pyxpcs.egg-info/PKG-INFO
writing dependency_links to src/pyxpcs.egg-info/dependency_links.txt
writing top-level names to src/pyxpcs.egg-info/top_level.txt
writing manifest file 'src/pyxpcs.egg-info/SOURCES.txt'
reading manifest file 'src/pyxpcs.egg-info/SOURCES.txt'
writing manifest file 'src/pyxpcs.egg-info/SOURCES.txt'
running build_ext
-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
-- pybind11 v2.6.1 dev1
-- Found PythonInterp: /opt/anaconda3/envs/VirEnv/bin/python (found version "3.7.5") 
-- Found PythonLibs: /opt/anaconda3/envs/VirEnv/lib/libpython3.7m.dylib
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Performing Test HAS_FLTO_THIN
-- Performing Test HAS_FLTO_THIN - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/qzhang234/pyXPCS_Test/pyxpcs/build/temp.macosx-10.7-x86_64-3.7
[ 66%] Building CXX object CMakeFiles/libpyxpcs.dir/src/libpyxpcs/sparse_data.cpp.o
[ 66%] Building CXX object CMakeFiles/libpyxpcs.dir/src/libpyxpcs/corr.cpp.o
/Users/qzhang234/pyXPCS_Test/pyxpcs/src/libpyxpcs/corr.cpp:6:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/libpyxpcs.dir/src/libpyxpcs/corr.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/libpyxpcs.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 75, in <module>
    zip_safe=False,
  File "/opt/anaconda3/envs/VirEnv/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/opt/anaconda3/envs/VirEnv/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/anaconda3/envs/VirEnv/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/anaconda3/envs/VirEnv/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/anaconda3/envs/VirEnv/lib/python3.7/site-packages/setuptools/command/develop.py", line 38, in run
    self.install_for_development()
  File "/opt/anaconda3/envs/VirEnv/lib/python3.7/site-packages/setuptools/command/develop.py", line 140, in install_for_development
    self.run_command('build_ext')
  File "/opt/anaconda3/envs/VirEnv/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/anaconda3/envs/VirEnv/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 32, in run
    self.build_extension(ext)
  File "setup.py", line 61, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/opt/anaconda3/envs/VirEnv/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.

```

</details>

**Comment by qzhang234** [comment]
I tried running `python setup.py develop` on kouga1g and got error message as well:

<details>
<summary> Terminal output </summary>

```
kouga1g% cd pyxpcs/
/home/beams/8IDIUSER/Piotr_XPCS/pyxpcs
kouga1g% python setup.py install
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 30] Read-only file system: '/APSshare/anaconda/x86_64/lib/python2.7/site-packages/test-easy-install-36315.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /APSshare/anaconda/x86_64/lib/python2.7/site-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.readthedocs.io/en/latest/easy_install.html

Please make the appropriate changes for your system and try again.

kouga1g% 
```

</details>
